;
; Game Engine Public Library
;
;

include GameEngine_vars.inc

extern GameEngine_Init:proc
extern GameEngine_Free:proc
extern GameEngine_PrintWord:proc
extern GameEngine_LoadGif:proc
extern GameEngine_ConvertImageToSprite:proc
extern GameEngine_DisplayFullScreenAnimatedImage:proc
extern GameEngine_DisplayCenteredImage:proc
extern GameEngine_DisplayTransparentImage:proc
extern GameEngine_ChangeState:proc
extern GameEngine_DisplaySprite:proc