;****************************************
;
;  Software 3D Public Header
;
;     Toby Opferman
;
;****************************************
extern Soft3D_Init:proc
extern Soft3D_Close:proc

extern Soft3D_SetCameraRotation:proc
extern Soft3D_SetViewDistance:proc
extern Soft3D_SetViewPoint:proc
extern Soft3D_SetAspectRatio:proc

extern Soft3D_DrawLine:proc
extern Soft3D_PlotPixel:proc
extern Soft3D_Convert3Dto2D:proc

include soft3d_structures.inc


