;****************************************
;
; VPal Public Definitions
;
;     Toby Opferman
;
;****************************************

extern VPal_SetColorIndex:proc
extern VPal_Create:proc
extern VPal_GetColorIndex:proc
extern VPal_Free:proc
extern VPal_Rotate:proc
extern VPal_RotateReset:proc
extern VPal_FindColorIndex:proc
extern VPal_CopyIndexRange:proc
extern VPal_MoveColorIndexes:proc
extern VPal_Transparent:proc
extern VPal_DirectAccess:proc
