copy apps\FullDemo\objfre_win7_amd64\amd64\*.exe binaries
copy Games\SpaceInvaders\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\BallTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\BrownianTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\BubbleTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\CopperTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\FireTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\FractalATest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\gifrottest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\GifTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\GifTestRt\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\PalTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\PlasmaTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\StarTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\TemplateTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\TttTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\WindowTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\WormTest\objfre_win7_amd64\amd64\*.exe binaries
copy TestApps\YourDemo\objfre_win7_amd64\amd64\*.exe binaries
copy apps\FullDemo\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy Games\SpaceInvaders\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\BallTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\BrownianTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\BubbleTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\CopperTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\FireTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\FractalATest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\gifrottest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\GifTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\GifTestRt\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\PalTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\PlasmaTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\StarTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\TemplateTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\TttTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\WindowTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\WormTest\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy TestApps\YourDemo\objfre_win7_amd64\amd64\*.pdb binaries\symbols
copy Games\SpaceInvaders\resources\* binaries
copy TestApps\gifrottest\resources\* binaries
copy TestApps\GifTest\resources\* binaries
copy TestApps\GifTestRt\resources\* binaries


