git add -f BallTest.exe
git add -f Brownian.exe
git add -f BubbleDemo.exe
git add -f CopperDemo.exe
git add -f FireDemo.exe
git add -f FractalADemo.exe
git add -f FullDemo.exe
git add -f GifRotTest.exe
git add -f GifTest.exe
git add -f GifTestrt.exe
git add -f PalDemo.exe
git add -f PlasmaDemo.exe
git add -f SpaceInvadersx64.exe
git add -f StarDemo.exe
git add -f symbols
git add -f TemplateDemo.exe
git add -f TttDemo.exe
git add -f WindowTest.exe
git add -f WormDemo.exe
git add -f YourDemoDemo.exe